apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root.poc-argocd-ms-01
  namespace: argocd
  labels:
    app.kubernetes.io/name: root.poc-argocd-ms-01
    app.kubernetes.io/part-of: poc-argocd-ms-01
    app.kubernetes.io/component: application
    app.kubernetes.io/version: v1.2.0
    app.kubernetes.io/instance: kind-local-argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fernandosoaresjr/poc-argocd-ms-01'
    targetRevision: poc-multi-cluster
    path: k8s/argo-apps/parent/
  destination:
    name: in-cluster
    namespace: argocd
    # server: 'https://kubernetes.default.svc'  # Local cluster for ArgoCD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
