apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root.poc-argocd-ms-01
  namespace: argocd
  labels:
    version: v2.1.0
spec:
  project: default
  source:
    repoURL: 'https://github.com/fernandosoaresjr/poc-argocd-ms-01'
    targetRevision: poc-multi-cluster
    path: k8s/argo-apps/parent/
  destination:
    name: in-cluster
    namespace: argocd
    # server: 'https://kubernetes.default.svc'  # Local cluster for ArgoCD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
