apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-01.poc-argocd-ms-01
  namespace: argocd
  labels:
    version: v2.2.0
spec:
  project: default
  source:
    helm:
      releaseName: cluster-01-poc-argocd-ms-01
      chart: ms
      parameters:
        - name: microservice.version
          value: 2.2.0
    repoURL: 'https://github.com/fernandosoaresjr/poc-argocd-ms-01'
    targetRevision: poc-multi-cluster
    path: k8s/microservice/
  destination:
    name: kind-local-01
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
