## Define the version of the microservice to be deployed
## The value of this key will be passed from the parent chart to the child chart
# version:

rollout:
  strategy:
    canary:
      maxSurge: "100%"
      steps:
        # In this PoC, we start the rollout with a pause but in the 
        # final implementation, we'll look at a metric in Datadog
        # to determine if the application deployed in the previous
        # cluster in the chain is healthy and the defined time period
        # has passed before starting, in fact, the step of the canary
        - pause: 1m
        - setWeight: 50
        - pause: {}

# Default configuration for all applications
application:
  name: poc-argocd-ms-01
  namespace: argocd
  project: default
  source:
    github:
      org: fernandosoaresjr
      repo: poc-argocd-ms-01
      targetRevision: poc-multi-cluster
      path: k8s/microservice/
  destination:
    namespace: default

applications:
  - cluster: kind-local-01
    clusterAlias: prd-01
    syncWave: 1
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    version: 2

  - cluster: in-cluster
    clusterAlias: prd-02
    namespace: default
    syncWave: 2
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    version: 2

  - cluster: in-cluster
    clusterAlias: prd-03
    syncWave: 3
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    version: 2
