## Define the version of the microservice to be deployed
## The value of this key will be passed from the parent chart to the child chart
# version:

# Default configuration for all applications
application:
  name: poc-argocd-ms-01
  namespace: argocd
  project: default
  source:
    github:
      org: fernandosoaresjr
      repo: poc-argocd-ms-01
      targetRevision: poc-multi-cluster
      path: k8s/microservice/
  destination:
    namespace: default

applications:
  - cluster: kind-local-01
    clusterAlias: prd-01
    syncWave: 1
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    # version:

  - cluster: in-cluster
    clusterAlias: prd-02
    namespace: default
    syncWave: 2
    # version:

  - cluster: in-cluster
    clusterAlias: prd-03
    syncWave: 3
    # version:
