apiVersion: v2
name: parent-multi-cluster-app
description: A Helm chart to deploy a parent application to manage multi-cluster ArgoCD applications

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0
