apiVersion: v2
name: ms
description: >
  This is a wrapper chart for the microservice chart, designed for use with ArgoCD. 
  The goal is to utilize the same Helm chart (microservice) to deploy all microservices, 
  avoiding the need to duplicate chart templates across multiple repositories. 
  By configuring this chart with a dependency on the microservice chart, 
  we ensure consistency and reduce maintenance overhead for ArgoCD Applications.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.0

dependencies:
  - name: microservice
    version: ">= 1.0.0"
    repository: "https://fernandosoaresjr.github.io/poc-argocd-helm/charts"

# TODO: Discuss with the team: 1) What we'll use as version number (semver, shacommit, tag, etc). 2) We should use the appVersion or other key in the values.yaml?
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# appVersion: "1.16.0"
