apiVersion: v1
kind: Service
metadata:
  name: poc-argocd-ms-01-stable
  labels:
    version: v1.4.0
spec:
  selector:
    app: poc-argocd-ms-01
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poc-argocd-ms-01-active
  labels:
    version: v1.4.0
spec:
  selector:
    app: poc-argocd-ms-01
  ports:
    - port: 80
      targetPort: 80
