## Define the version of the microservice to be deployed
## The value of this key will be passed from the child chart to the microservice chart
# microservice:
#   version:

microservice:
  rollout:
    strategy:
      canary:
        maxSurge: "100%"
        steps:
          # In this PoC, we start the rollout with a pause but in the 
          # final implementation, we'll look at a metric in Datadog
          # to determine if the application deployed in the previous
          # cluster in the chain is healthy and the defined time period
          # has passed before starting, in fact, the step of the canary
          - pause: {}
          - setWeight: 50
          - pause: {}
          # - pause: { duration: 1m }
          # - setWeight: 50
          # - pause: { duration: 1m }

job:
  enabled: false
