# range over .Values.applications
{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .clusterAlias }}.{{ $.Values.application.name }}"
  namespace: {{ $.Values.application.namespace }}
  labels:
    microservice: "true"
    version: "v{{ $.Values.version }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: {{ $.Values.application.project }}
  source:
    # Can point to either a Helm chart repo or a git repo.
    # In this case, we are pointing to a git repo.
    repoURL: "https://github.com/{{ $.Values.application.source.github.org }}/{{ $.Values.application.source.github.repo }}"
    # For Helm, this refers to the chart version.
    # For git, this refers to the git revision (e.g. branch, tag, commit).
    targetRevision: {{ $.Values.application.source.github.targetRevision }}
    # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
    # For git, this refers to the path within the repo.
    path: {{ $.Values.application.source.github.path }}
    # helm specific config
    helm:
      # Release name override (defaults to application name)
      # We need to set this because we are using `.` in the application name, which is not allowed in Helm release names
      releaseName: "{{ .clusterAlias }}-{{ $.Values.application.name }}"
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      # This is equivalent to `--set microservice.version={{ .version }}`
      # We'll use this as hack to set the version of the microservice, in order to achieve the desired behavior of deploying in multi-cluster
      parameters:
        - name: microservice.version
          value: {{ $.Values.version }}
  destination:
    name: {{ .cluster }}
    namespace: {{ $.Values.application.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
