# range over .Values.applications
{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .clusterAlias }}.{{ $.Values.application.name }}"
  namespace: {{ $.Values.application.namespace }}
  labels:
    microservice: "true"
    version: "v{{ $.Values.version }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave }}"
spec:
  project: {{ $.Values.application.project }}
  source:
    repoURL: "https://github.com/{{ $.Values.application.source.github.org }}/{{ $.Values.application.source.github.repo }}"
    targetRevision: {{ $.Values.application.source.github.targetRevision }}
    path: {{ $.Values.application.source.github.path }}
    helm:
      releaseName: "{{ .clusterAlias }}-{{ $.Values.application.name }}"
      parameters:
        - name: microservice.version
          value: {{ $.Values.version }}
  destination:
    name: {{ .cluster }}
    namespace: {{ $.Values.application.destination.namespace }}
  {{- with .syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
---
{{- end }}
